# Generated by Django 4.1.7 on 2023-09-14 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(max_length=20)),
                ('subscription_id', models.CharField(max_length=255)),
                ('commitment_or_billing', models.CharField(max_length=255)),
                ('product_name', models.CharField(max_length=255)),
                ('domain_name', models.CharField(max_length=255)),
                ('qty', models.IntegerField()),
                ('license_type', models.CharField(max_length=255)),
                ('vendor_name', models.CharField(max_length=255)),
                ('current_active_qty', models.IntegerField()),
                ('erp', models.CharField(max_length=255)),
                ('customer', models.CharField(max_length=255)),
                ('qut_no', models.CharField(max_length=255)),
                ('invoice_no', models.CharField(max_length=255)),
                ('create_sales_order', models.BooleanField(default=False)),
            ],
        ),
    ]
