# Generated by Django 4.1.7 on 2023-09-14 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenseorder',
            name='start_date',
            field=models.DateField(blank=True, max_length=20, null=True),
        ),
    ]
