# Generated by Django 4.1.7 on 2023-09-14 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_licenseorder_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenseorder',
            name='start_date',
            field=models.DateField(default=None, max_length=20),
        ),
    ]
